### ISSUE TITLE
Failed auth when using cloud provider Openstack with kubespray

### ISSUE THREAD

**Issue by jianzj** [kubespray/kubespray-cli#102]
During using openstack as cloud provide, I just found a tiny error , which will block kubespray create VMs. 

As there is a python syntax erro on cloud.py file and parameter `domain_name` will not be set , so it will block all actions when try to use openstack cloud with keystone v3 authentication. All authentication will be failed with 400 error, due to lack of domain , or you will find this issue when trying to initial your environment . 

```
root@jianzj-ansible:~/kubespary# kubespray openstack --config kubespray.yml --masters 2 --nodes 2 --etcds 3 --noclone --cluster-name jianzj
Traceback (most recent call last):
  File "/usr/local/bin/kubespray", line 422, in <module>
    args.func(config)
  File "/usr/local/bin/kubespray", line 65, in openstack
    O.gen_openstack_playbook()
  File "/usr/local/lib/python2.7/dist-packages/kubespray/cloud.py", line 308, in gen_openstack_playbook
    openstack_auth.update({'domain_name': self.options[os_domain_name]})
NameError: global name 'os_domain_name' is not defined
```

I create a PR to fix , hope it will help https://github.com/kubespray/kubespray-cli/pull/101 . 

Sorry for not following the rules of contribution as I did not find related doc.

**Comment by jianzj** [comment]
As PR is merged , this issue could be closed
